extends: "airbnb-base"
rules:
    "indent": ["error", 4, { "SwitchCase": 1 }]
    "class-methods-use-this": [0]
    "no-console": [0]
    "no-plusplus": [0]
    "no-underscore-dangle": ["error", { allowAfterThis: true }]
    "no-else-return": [0]
    "quotes": ["error", "single", { avoidEscape: true }]
    "import/no-extraneous-dependencies": [0]
